// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWtC87vWGuLT1Qyg3VkwxKJeZ_31bd2U',
    appId: '1:34297406703:web:dcd5f3fc990ccec28f671a',
    messagingSenderId: '34297406703',
    projectId: 'task-1-e5635',
    authDomain: 'task-1-e5635.firebaseapp.com',
    databaseURL: 'https://task-1-e5635-default-rtdb.firebaseio.com',
    storageBucket: 'task-1-e5635.appspot.com',
    measurementId: 'G-6NW4KCEPEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4UTdQ8pKR9IqNC8a0YsMA9dDw3-UGxVU',
    appId: '1:34297406703:android:750d2d49654c7c938f671a',
    messagingSenderId: '34297406703',
    projectId: 'task-1-e5635',
    databaseURL: 'https://task-1-e5635-default-rtdb.firebaseio.com',
    storageBucket: 'task-1-e5635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAd6GbkHOO_vrUcvP9Mr_yduVC7edzvQ',
    appId: '1:34297406703:ios:9054932a9da6adfa8f671a',
    messagingSenderId: '34297406703',
    projectId: 'task-1-e5635',
    databaseURL: 'https://task-1-e5635-default-rtdb.firebaseio.com',
    storageBucket: 'task-1-e5635.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAAd6GbkHOO_vrUcvP9Mr_yduVC7edzvQ',
    appId: '1:34297406703:ios:1c292838301422ae8f671a',
    messagingSenderId: '34297406703',
    projectId: 'task-1-e5635',
    databaseURL: 'https://task-1-e5635-default-rtdb.firebaseio.com',
    storageBucket: 'task-1-e5635.appspot.com',
    iosBundleId: 'com.example.task1.RunnerTests',
  );
}
